# Generated by Django 4.2.10 on 2024-03-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='headquarter_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
