# Generated by Django 4.2.10 on 2024-03-20 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_skillcategory_skill_created_by_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
    ]
