# Generated by Django 4.2.10 on 2024-03-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_skill_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userskill',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
