# Generated by Django 4.2.10 on 2024-03-21 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_department_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
