# Generated by Django 4.2.10 on 2024-03-21 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_department_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_id', to='users.organization'),
        ),
    ]
